'use server';
/**
 * @fileOverview An AI agent that answers student questions using a chatbot interface.
 *
 * - answerQuestionWithAIChatbot - A function that handles the question answering process.
 * - AnswerQuestionWithAIChatbotInput - The input type for the answerQuestionWithAIChatbot function.
 * - AnswerQuestionWithAIChatbotOutput - The return type for the answerQuestionWithAIChatbot function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerQuestionWithAIChatbotInputSchema = z.object({
  question: z.string().describe('The question to be answered by the chatbot.'),
});
export type AnswerQuestionWithAIChatbotInput = z.infer<typeof AnswerQuestionWithAIChatbotInputSchema>;

const AnswerQuestionWithAIChatbotOutputSchema = z.object({
  answer: z.string().describe('The answer generated by the AI chatbot.'),
});
export type AnswerQuestionWithAIChatbotOutput = z.infer<typeof AnswerQuestionWithAIChatbotOutputSchema>;

export async function answerQuestionWithAIChatbot(input: AnswerQuestionWithAIChatbotInput): Promise<AnswerQuestionWithAIChatbotOutput> {
  return answerQuestionWithAIChatbotFlow(input);
}

const prompt = ai.definePrompt({
  name: 'answerQuestionWithAIChatbotPrompt',
  input: {schema: AnswerQuestionWithAIChatbotInputSchema},
  output: {schema: AnswerQuestionWithAIChatbotOutputSchema},
  prompt: `You are a helpful AI chatbot assisting students with their studies.

  Answer the following question to the best of your ability:

  Question: {{{question}}}`,
});

const answerQuestionWithAIChatbotFlow = ai.defineFlow(
  {
    name: 'answerQuestionWithAIChatbotFlow',
    inputSchema: AnswerQuestionWithAIChatbotInputSchema,
    outputSchema: AnswerQuestionWithAIChatbotOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
