
export const academicData = {
  universites: [
    {
      "name": "UNIVERSITE D ALGER 1", "type": "universite",
      "specializations": ["SCIENCES DE LA MATIERE"]
    },
    {
      "name": "UNIVERSITE D ALGER 2", "type": "universite",
      "specializations": ["LANGUE TURQUE", "LANGUE CHINOISE", "SCIENCES HUMAINES ARCHEOLOGIE", "SCIENCES HUMAINES BIBLIOTHECONOMIE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "ARTS", "LANGUE ET LITTERATURE ARABES"]
    },
    {
      "name": "UNIVERSITE D ALGER 3", "type": "universite",
      "specializations": ["SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "ECONOMIE QUANTITATIVE ET INFORMATIQUE", "ECONOMIE ET RELATIONS INTERNATIONALES", "SCIENCES POLITIQUES"]
    },
    {
      "name": "UNIVERSITE ALGER 1 + ALGER 3", "type": "universite",
      "specializations": ["MATHEMATIQUES APPLIQUEE + SCIENCES ECONOMIQUES"]
    },
    {
      "name": "UNIVERSITE DE BEJAIA", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "GENIE CIVIL", "GENIE DES PROCEDES", "HYDRAULIQUE", "ELECTROTECHNIQUE", "GENIE MECANIQUE", "SCIENCES DE LA MATIERE", "INFORMATIQUE", "MATHEMATIQUES", "INFORMATIQUE + SCIENCES ECONOMIQUES", "SCIENCES DE LA NATURE ET DE LA VIE", "SCIENCES ALIMENTAIRES (FORMATIONS PROFESSIONNALISANTES)", "SCIENCES ALIMENTAIRES", "DROIT", "INFORMATIQUE + DROIT", "LANGUE FRANCAISE", "TRADUCTION INTERPRETARIAT (ARABE, FRANCAIS, AMAZIGH)", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "SCIENCES ET TECHNIQUES DES ACTIVITES PHYSIQUES ET SPORTIVES", "LANGUE ET CULTURE AMAZIGHES", "ARCHITECTURE", "ARCHITECTURE + SCIENCES SOCIALES (SOCIOLOGIE)", "MEDECINE + INFORMATIQUE"]
    },
    {
      "name": "UNIVERSITE DE BLIDA 1", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "ELECTROTECHNIQUE", "GENIE MECANIQUE", "SCIENCES DE LA MATIERE", "INFORMATIQUE", "MATHEMATIQUES", "SCIENCES DE LA NATURE ET DE LA VIE", "SCIENCES AGRONOMIQUES", "URBANISME", "ARCHITECTURE", "ENERGIES RENOUVELABLES (CONVERSION PHOTOVOLTAIQUE)"]
    },
    {
      "name": "UNIVERSITE DE BOUIRA", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "GENIE CIVIL", "GENIE DES PROCEDES", "ELECTROTECHNIQUE", "GENIE MECANIQUE", "SCIENCES DE LA MATIERE", "INFORMATIQUE", "MATHEMATIQUES", "SCIENCES DE LA NATURE ET DE LA VIE", "SCIENCES AGRONOMIQUES", "SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "DROIT", "LANGUE FRANCAISE", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "SCIENCES ISLAMIQUES", "SCIENCES ET TECHNIQUES DES ACTIVITES PHYSIQUES ET SPORTIVES", "LANGUE ET LITTERATURE ARABES", "LANGUE ET CULTURE AMAZIGHES"]
    },
    {
      "name": "UNIVERSITE DE BATNA 1", "type": "universite",
      "specializations": ["SCIENCES DE LA MATIere", "SCIENCES DE LA NATURE ET DE LA VIE", "SCIENCES AGRONOMIQUES", "SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "SCIENCES POLITIQUES", "DROIT", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "SCIENCES ISLAMIQUES", "LANGUE ET LITTERATURE ARABES", "LANGUE ET CULTURE AMAZIGHES", "GESTION DES TECHNIQUES URBAINES", "MANAGEMENT DES PROJETS DE CONSTRUCTION (FORMATIONS PROFESSIONNALISANTES)", "ARCHITECTURE"]
    },
    {
      "name": "UNIVERSITE DE BATNA 2", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "GENIE CIVIL", "GENIE DES PROCEDES", "ELECTROTECHNIQUE", "GENIE MECANIQUE (TECHNOLOGIE AUTOMOBILE)", "GENIE MECANIQUE", "HYGIENE ET SECURITE INDUSTRIELLE (FORMATIONS PROFESSIONNALISANTES)", "HYGIENE ET SECURITE INDUSTRIELLE", "INFORMATIQUE", "MATHEMATIQUES", "GEOGRAPHIE ET AMENAGEMENT DU TERRITOIRE", "GEOLOGIE", "LANGUE FRANCAISE", "TRADUCTION INTERPRETARIAT (ARABE, FRANCAIS, ANGLAIS)", "LANGUE ANGLAISE", "SCIENCES ET TECHNIQUES DES ACTIVITES PHYSIQUES ET SPORTIVES", "MEDECINE + INFORMATIQUE"]
    },
    {
      "name": "UNIVERSITE DE BISKRA", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "GENIE CIVIL", "GENIE DES PROCEDES", "HYDRAULIQUE", "ELECTROTECHNIQUE (ENERGIES RENOUVELABLES)", "ELECTROTECHNIQUE", "GENIE MECANIQUE", "SCIENCES DE LA MATIERE", "PHYSIQUE (FORMATIONS PROFESSIONNALISANTES)", "INFORMATIQUE (FORMATIONS PROFESSIONNALISANTES)", "INFORMATIQUE", "MATHEMATIQUES", "SCIENCES DE LA NATURE ET DE LA VIE", "SCIENCES AGRONOMIQUES", "GEOGRAPHIE ET AMENAGEMENT DU TERRITOIRE", "GEOLOGIE", "SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "SCIENCES POLITIQUES", "DROIT", "LANGUE FRANCAISE", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "SCIENCES ET TECHNIQUES DES ACTIVITES PHYSIQUES ET SPORTIVES", "LANGUE ET LITTERATURE ARABES", "GESTION DES TECHNIQUES URBAINES", "MANAGEMENT DES PROJETS DE CONSTRUCTION (FORMATIONS PROFESSIONNALISANTES)", "ARCHITECTURE", "SCIENCES VETERINAIRES"]
    },
    {
      "name": "UNIVERSITE DE CHLEF", "type": "universite",
      "specializations": ["SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "SCIENCES POLITIQUES", "DROIT", "LANGUE FRANCAISE", "TRADUCTION INTERPRETARIAT (ARABE, FRANCAIS, ANGLAIS)", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "SCIENCES ET TECHNIQUES DES ACTIVITES PHYSIQUES ET SPORTIVES", "LANGUE ET LITTERATURE ARABES", "GESTION DES TECHNIQUES URBAINES", "ARCHITECTURE", "SCIENCES ET TECHNOLOGIES", "GENIE CIVIL", "GENIE DES PROCEDES", "ELECTROTECHNIQUE", "GENIE MECANIQUE", "SCIENCES DE LA MATIERE", "INFORMATIQUE", "MATHEMATIQUES", "SCIENCES DE LA NATURE ET DE LA VIE", "SCIENCES AGRONOMIQUES", "GEOGRAPHIE ET AMENAGEMENT DU TERRITOIRE", "GEOLOGIE"]
    },
    {
      "name": "UNIVERSITE DE CONSTANTINE 1", "type": "universite",
      "specializations": ["DROIT", "LANGUE FRANCAISE", "TRADUCTION INTERPRETARIAT (ARABE, FRANCAIS, ANGLAIS)"]
    },
    {
      "name": "UNIVERSITE DES SCIENCES ISLAMIQUES EMIR ABDELKADER", "type": "universite",
      "specializations": ["SCIENCES ISLAMIQUES", "LANGUE ET LITTERATURE ARABES"]
    },
    {
      "name": "UNIVERSITE DE GHARDAIA", "type": "universite",
      "specializations": ["SCIENCES SOCIALES", "SCIENCES ISLAMIQUES", "LANGUE ET LITTERATURE ARABES", "SCIENCES ET TECHNOLOGIES", "GENIE CIVIL"]
    },
    {
      "name": "UNIVERSITE DE JIJEL", "type": "universite",
      "specializations": ["ELECTROTECHNIQUE", "GENIE MECANIQUE", "SCIENCES DE LA MATIERE", "INFORMATIQUE", "MATHEMATIQUES", "SCIENCES DE LA NATURE ET DE LA VIE", "LANGUE ET LITTERATURE ARABES", "GESTION DES TECHNIQUES URBAINES (GENIE URBAIN)", "GESTION DES TECHNIQUES URBAINES (GESTION DES VILLES)", "ARCHITECTURE"]
    },
    {
      "name": "UNIVERSITE DE KHENCHELA", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "GENIE CIVIL", "SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "SCIENCES POLITIQUES", "DROIT", "LANGUE FRANCAISE", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "LANGUE ET LITTERATURE ARABES"]
    },
    {
      "name": "UNIVERSITE DE LAGHOUAT", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "GENIE CIVIL (CONSTRUCTIONS CIVILS ET ENVIRONNEMENT)", "GENIE CIVIL (VOIRIE ET RESEAUX DIVERS)", "GENIE CIVIL", "GENIE DES PROCEDES", "ELECTROTECHNIQUE", "TRAVAUX PUBLICS", "GENIE MECANIQUE", "SCIENCES DE LA MATIERE", "INFORMATIQUE", "MATHEMATIQUES", "MATHEMATIQUES APPLIQUEES + SCIENCES ECONOMIQUES", "SCIENCES DE LA NATURE ET DE LA VIE", "SCIENCES AGRONOMIQUES", "SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "SCIENCES ECONOMIQUES (A DISTANCE)", "SCIENCES POLITIQUES", "DROIT", "LANGUE FRANCAISE", "LANGUE ESPAGNOLE", "TRADUCTION INTERPRETARIAT (ARABE, FRANCAIS, ANGLAIS)", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "SCIENCES ISLAMIQUES", "INFORMATIQUE + SCIENCES DE L INFORMATION ET DE LA COMMUNICATION", "SCIENCES ET TECHNIQUES DES ACTIVITES PHYSIQUES ET SPORTIVES", "LANGUE ET LITTERATURE ARABES", "GESTION DES TECHNIQUES URBAINES", "ARCHITECTURE", "SCIENCES VETERINAIRES"]
    },
    {
      "name": "UNIVERSITE DE MOSTAGANEM", "type": "universite",
      "specializations": ["SCIENCES AGRONOMIQUES", "SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "SCIENCES COMMERCIALES (FORMATIONS PROFESSIONNALISANTES)", "SCIENCES POLITIQUES", "DROIT", "LANGUE FRANCAISE", "LANGUE ESPAGNOLE", "TRADUCTION INTERPRETARIAT (ARABE, FRANCAIS, ANGLAIS)", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "SCIENCES ISLAMIQUES", "SCIENCES ET TECHNIQUES DES ACTIVITES PHYSIQUES ET SPORTIVES", "ARTS", "LANGUE ET LITTERATURE ARABES", "ARCHITECTURE"]
    },
    {
      "name": "UNIVERSITE DE NAAMA", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "GENIE CIVIL", "ELECTROTECHNIQUE", "GENIE MECANIQUE", "SCIENCES DE LA MATIERE", "INFORMATIQUE", "MATHEMATIQUES", "LANGUE ET LITTERATURE ARABES"]
    },
    {
      "name": "UNIVERSITE D ORAN 1 – I.S.T.A", "type": "universite",
      "specializations": ["INFORMATIQUE + SCIENCES DE GESTION", "SCIENCES DE GESTION", "SCIENCES FINANCIERES ET COMPTABILITE (FORMATIONS PROFESSIONNALISANTES)"]
    },
    {
      "name": "UNIVERSITE D ORAN 2", "type": "universite",
      "specializations": ["ELECTROMECANIQUE", "GENIE INDUSTRIELLE", "HYGIENE ET SECURITE INDUSTRIELLE", "GEOGRAPHIE ET AMENAGEMENT DU TERRITOIRE", "GEOLOGIE", "SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "SCIENCES POLITIQUES", "DROIT", "LANGUE FRANCAISE", "LANGUE ESPAGNOLE", "LANGUE ALLEMANDE", "LANGUE RUSSE", "LANGUE ANGLAISE", "LANGUE ANGLAISE + SCIENCES POLITIQUES", "SCIENCES SOCIALES"]
    },
    {
      "name": "UNIVERSITE DE OUARGLA", "type": "universite",
      "specializations": ["MEDECINE + INFORMATIQUE", "MEDECINE + SCIENCES ECONOMIQUES"]
    },
    {
      "name": "UNIVERSITE DE OUM EL BOUAGHI", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "GENIE CIVIL", "GENIE DES PROCEDES", "ELECTROTECHNIQUE", "GENIE MECANIQUE", "SCIENCES DE LA MATIERE", "INFORMATIQUE", "MATHEMATIQUES", "SCIENCES DE LA NATURE ET DE LA VIE", "SCIENCES AGRONOMIQUES", "GEOGRAPHIE ET AMENAGEMENT DU TERRITOIRE", "GEOLOGIE", "SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "SCIENCES POLITIQUES", "DROIT", "LANGUE FRANCAISE", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "SCIENCES ET TECHNIQUES DES ACTIVITES PHYSIQUES ET SPORTIVES", "ARTS", "LANGUE ET LITTERATURE ARABES", "GESTION DES TECHNIQUES URBAINES", "METIERS DE LA VILLE (DESIGN ET ARCHITECTURE INTERIEURE)", "METIERS DE LA VILLE (INFOGRAPHIE EN ARCHITECTURE)", "ARCHITECTURE"]
    },
    {
      "name": "UNIVERSITE DE RELIZANE", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES"]
    },
    {
      "name": "UNIVERSITE DE SAIDA", "type": "universite",
      "specializations": ["ELECTROTECHNIQUE", "SCIENCES DE LA MATIERE", "INFORMATIQUE", "MATHEMATIQUES"]
    },
    {
      "name": "UNIVERSITE DE SIDI BEL ABBES", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "GENIE CIVIL", "GENIE DES PROCEDES", "ELECTROTECHNIQUE", "ELECTRONIQUE (SYSTEMES ELECTRONIQUES AUTONOMES ET INTELLIGENCE ARTIFICIELLE)", "GENIE MECANIQUE", "SCIENCES DE LA MATIERE", "INFORMATIQUE", "MATHEMATIQUES", "SCIENCES DE LA NATURE ET DE LA VIE", "SCIENCES AGRONOMIQUES", "SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "SCIENCES COMMERCIALES (FORMATIONS PROFESSIONNALISANTES)", "SCIENCES POLITIQUES", "DROIT", "LANGUE FRANCAISE", "LANGUE ALLEMANDE", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIences SOCIALES", "ARTS", "LANGUE ET LITTERATURE ARABES"]
    },
    {
      "name": "UNIVERSITE DE SKIKDA", "type": "universite",
      "specializations": ["SCIENCES HUMAINES", "SCIENCES SOCIALES", "LANGUE ET LITTERATURE ARABES", "AUTOMATIQUE (FORMATIONS PROFESSIONNALISANTES)", "HYGIENE ET SECURITE INDUSTRIELLE (FORMATIONS PROFESSIONNALISANTES)"]
    },
    {
      "name": "UNIVERSITE DE SOUK AHRAS", "type": "universite",
      "specializations": ["SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "DROIT", "LANGUE FRANCAISE", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "SCIENCES ET TECHNIQUES DES ACTIVITES PHYSIQUES ET SPORTIVES", "LANGUE ET LITTERATURE ARABES", "SCIENCES VETERINAIRES"]
    },
    {
      "name": "UNIVERSITE DE TAMANRASSET", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "GENIE CIVIL", "ELECTROTECHNIQUE", "GENIE MECANIQUE", "SCIENCES DE LA MATIERE", "INFORMATIQUE", "MATHEMATIQUES", "SCIENCES DE LA NATURE ET DE LA VIE", "GEOLOGIE", "SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "SCIENCES POLITIQUES", "DROIT", "LANGUE FRANCAISE", "LANGUE ANGLAISE"]
    },
    {
      "name": "UNIVERSITE DE TEBESSA", "type": "universite",
      "specializations": []
    },
    {
      "name": "UNIVERSITE DE TIARET", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "GENIE CIVIL", "ELECTROTECHNIQUE", "GENIE MECANIQUE", "INFORMATIQUE", "MATHEMATIQUES", "SCIENCES AGRONOMIQUES", "GEOGRAPHie ET AMENAGEMENT DU TERRITOIRE", "SCIENCES POLITIQUES", "LANGUE FRANCAISE", "LANGUE ESPAGNOLE", "LANGUE ALLEMANDE", "LANGUE ANGLAISE", "ARTS", "SCIENCES DE LA MATIERE"]
    },
    {
      "name": "UNIVERSITE DE TIPAZA", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "GENIE CIVIL", "GENIE DES PROCEDES", "MATHEMATIQUES", "SCIENCES DE LA NATURE ET DE LA VIE"]
    },
    {
      "name": "UNIVERSITE DE TISSEMSILT", "type": "universite",
      "specializations": ["SCIENCES AGRONOMIQUES", "SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "DROIT", "LANGUE FRANCAISE", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "SCIENCES ET TECHNIQUES DES ACTIVITES PHYSIQUES ET SPORTIVES", "LANGUE ET LITTERATURE ARABES"]
    },
    {
      "name": "UNIVERSITE DE TLEMCEN", "type": "universite",
      "specializations": ["INFORMATIQUE", "MATHEMATIQUES", "SCIENCES DE LA NATURE ET DE LA VIE", "SCIENCES AGRONOMIQUES", "LANGUE ANGLAISE + SCIENCES FINANCIERES ET COMPTABILITE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "SCIENCES ISLAMIQUES", "ARTS", "LANGUE ET LITTERATURE ARABES", "ARCHITECTURE", "MEDECINE + PSYCHOLOGIE"]
    },
    {
      "name": "UNIVERSITE DE TLEMCEN – I.S.T.A", "type": "universite",
      "specializations": ["GENIE CIVIL (FORMATIONS PROFESSIONNALISANTES)"]
    },
    {
      "name": "UNIVERSITE D ADRAR", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "GENIE CIVIL", "GENIE DES PROCEDES", "ELECTROTECHNIQUE", "GENIE MECANIQUE", "SCIENCES DE LA MATIERE", "INFORMATIQUE", "MATHEMATIQUES", "SCIENCES DE LA NATURE ET DE LA VIE", "SCIENCES AGRONOMIQUES", "SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "SCIENCES POLITIQUES", "DROIT", "LANGUE FRANCAISE", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "SCIENCES ISLAMIQUES", "LANGUE ET LITTERATURE ARABES", "ARCHITECTURE"]
    },
    {
      "name": "UNIVERSITE D AIN TEMOUCHENT", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "GENIE CIVIL", "GENIE DES PROCEDES", "ELECTROTECHNIQUE", "LANGUE ESPAGNOLE", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "LANGUE ET LITTERATURE ARABES"]
    },
    {
      "name": "UNIVERSITE D EL BAYADH", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "GENIE CIVIL", "ELECTROTECHNIQUE", "SCIENCES SOCIALES", "SCIENCES ET TECHNIQUES DES ACTIVITES PHYSIQUES ET SPORTIVES", "LANGUE ET LITTERATURE ARABES"]
    },
    {
      "name": "UNIVERSITE D EL TARF", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "SCIENCES DE LA MATIERE", "INFORMATIQUE", "MATHEMATIQUES", "SCIENCES DE LA NATURE ET DE LA VIE", "SCIENCES AGRONOMIQUES", "LANGUE ET LITTERATURE ARABES", "SCIENCES VETERINAIRES"]
    },
    {
      "name": "UNIVERSITE DE BORDJ BOU ARRERIDJ", "type": "universite",
      "specializations": ["SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "DROIT", "LANGUE FRANCAISE", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "SCIENCES ISLAMIQUES", "LANGUE ET LITTERATURE ARABES"]
    },
    {
      "name": "UNIVERSITE DE BARIKA", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "INFORMATIQUE", "MATHEMATIQUES", "SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "DROIT", "LANGUE FRANCAISE", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "LANGUE ET LITTERATURE ARABES"]
    },
    {
      "name": "UNIVERSITE DE ILLIZI", "type": "universite",
      "specializations": ["SCIENCES ECONOMIQUES, DE GESTion ET COMMERCIALES", "DROIT", "LANGUE ANGLAISE", "SCIENCES SOCIALES", "INFORMATIQUE"]
    },
    {
      "name": "UNIVERSITE DE AFLOU", "type": "universite",
      "specializations": ["INFORMATIQUE", "SCIENCES DE LA NATURE ET DE LA VIE", "SCIENCES ECONOMIQUES, DE GESTION ET COMMERCIALES", "DROIT", "LANGUE FRANCAISE", "LANGUE ANGLAISE", "SCIENCES HUMAINES", "SCIENCES SOCIALES", "LANGUE ET LITTERATURE ARABES"]
    },
    {
      "name": "UNIVERSITE DE BOUMERDES", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES", "AUTOMATIQUE", "HYDROCARBURES (TECHNOLOGIES DE TRAITEMENT DU PETROLE ET DU GAZ)", "HYDROCARBURES", "GENIE CIVIL", "ELECTROMECANIQUE", "GENIE DES PROCEDES", "ELECTROTECHNIQUE", "ELECTRONIQUE (ENSEIGNEMENT EN LANGUE ANGLAISE)", "GENIE MECANIQUE (INGENIERIE DE CONSTRUCTION AUTOMOBILE)", "GENIE MECANIQUE", "SCIENCES ET TECHNIQUES DES ACTIVITES PHYSIQUES ET SPORTIVES", "LANGUE ET LITTERATURE ARABES"]
    },
    {
      "name": "UNIVERSITE DE MEDEA", "type": "universite",
      "specializations": ["SCIENCES ET TECHNOLOGIES"]
    },
    {
      "name": "UNIVERSITE DE TIZI OUZOU", "type": "universite",
      "specializations": ["SCIENCES HUMAINES", "SCIENCES SOCIALES", "LANGUE ET LITTERATURE ARABES", "LANGUE ET CULTURE AMAZIGHES", "ARCHITECTURE"]
    },
    {
      "name": "INSTITUT VETERINAIRE – UNIV. TIARET", "type": "universite",
      "specializations": ["SCIENCES VETERINAIRES"]
    },
    {
      "name": "INSTITUT VETERINAIRE – UNIV. BATNA 1", "type": "universite",
      "specializations": ["SCIENCES VETERINAIRES"]
    }
  ],
  ecoles: [
    {
      "name": "ECOLE NATIONALE POLYTECHNIQUE D ALGER", "type": "ecole",
      "specializations": ["FB ST ECOLE NATIONALE POLYTECHNIQUE D ALGER"]
    },
    {
      "name": "ECOLE NATIONALE SUPERIEURE AGRONOMIQUE ALGER", "type": "ecole",
      "specializations": ["FB SNV ECOLE NATIONALE SUPERIEURE AGRONOMIQUE ALGER"]
    },
    {
      "name": "ECOLE DES HAUTES ETUDES COMMERCIALES KOLEA", "type": "ecole",
      "specializations": ["FB SECSG ECOLE DES HAUTES ETUDES COMMERCIALES KOLEA"]
    },
    {
      "name": "ECOLE SUPERIEURE DE COMMERCE KOLEA", "type": "ecole",
      "specializations": ["FB SECSG ECOLE SUPERIEURE DE COMMERCE KOLEA"]
    },
    {
      "name": "ECOLE NATIONALE SUPERIEURE EN STATISTIQUE ET EN ECONOMIE APPLIQUEE DE KOLEA", "type": "ecole",
      "specializations": ["FB SECSG ECOLE NATIONALE SUPERIEURE EN STATISTIQUE ET EN ECONOMIE APPLIQUEE KOLEA"]
    },
    {
      "name": "ECOLE NATIONALE SUPERIEURE DES TRAVAUX PUBLICS ALGER", "type": "ecole",
      "specializations": ["FB ST ECOLE NATIONALE SUPERIEURE DES TRAVAUX PUBLICS ALGER"]
    },
    {
      "name": "ECOLE NATIONALE SUPERIEURE EN INFORMATIQUE ALGER", "type": "ecole",
      "specializations": ["FB INF ECOLE NATIONALE SUPERIEURE EN INFORMATIQUE ALGER"]
    },
    {
      "name": "ECOLE NATIONALE SUPERIEURE DES TECHNOLOGIES AVANCEES ALGER", "type": "ecole",
      "specializations": ["FB ST ECOLE NATIONALE SUPERIEURE DES TECHNOLOGIES AVANCEES ALGER", "FB INF ECOLE NATIONALE SUPERIEURE DES TECHNOLOGIES AVANCEES ALGER"]
    },
    {
      "name": "ECOLE NATIONALE SUPERIEURE DES SYSTEMES AUTONOMES ALGER", "type": "ecole",
      "specializations": ["FB ST ECOLE NATIONALE SUPERIEURE DES SYSTEMES AUTONOMES ALGER"]
    },
    {
      "name": "ECOLE NATIONALE SUPERIEURE DES NANOSCIENCES ET NANOTECHENOLOGIES ALGER", "type": "ecole",
      "specializations": ["FB ST ECOLE NATIONALE SUPERIEURE DES NANOSCIENCES ET NANOTECHENOLOGIES ALGER"]
    },
    {
      "name": "ECOLE NATIONALE SUPERIEURE DE CYBER SECURITE ALGER", "type": "ecole",
      "specializations": ["FB INF ECOLE NATIONALE SUPERIEURE DE CYBER SECURITE ALGER"]
    },
    {
      "name": "ECOLE NATIONALE SUPERIEURE EN INTELLIGENCE ARTIFICIELLE ALGER", "type": "ecole",
      "specializations": ["FB INF ECOLE NATIONALE SUPERIEURE EN INTELLIGENCE ARTIFICIELLE ALGER"]
    },
    {
      "name": "ECOLE NATIONALE SUPERIEURE EN MATHEMATIQUES ALGER", "type": "ecole",
      "specializations": ["FB MATHS ECOLE NATIONALE SUPERIEURE EN MATHEMATIQUES ALGER"]
    },
    {
      "name": "ECOLE POLYTECHNIQUE D ARCHITECTURE ET D URBANISME ALGER", "type": "ecole",
      "specializations": ["FB SP ECOLE POLYTECHNIQUE D ARCHITECTURE ET D URBANISME ALGER"]
    },
    {
      "name": "ECOLE NATIONALE SUPERIEURE VETERINAIRE ALGER", "type": "ecole",
      "specializations": ["SCIENCES VETERINAIRES"]
    },
    {
      "name": "ECOLE SUPERIEURE DES SCIENCES DE L ALIMENT ET DES INDUSTRIES AGROALIMENTAIRES ALGER", "type": "ecole",
      "specializations": ["FB SNV ECOLE SUPERIEURE DES SCIENCES DE L ALIMENT ET DES INDUSTRIES AGROALIMENTAIRES D ALGER"]
    },
    {
      "name": "ECOLE NORMALE SUPERIEURE KOUBA (E.N.S)", "type": "ecole",
      "specializations": ["MUSIQUE(P.E.S)", "SCIENCES NATURELLES(P.E.S)", "SCIENCES PHYSIQUE ET TECHNOLOGIE(P.E.M)"]
    },
    {
      "name": "ECOLE NORMALE SUPERIEURE DE BOUZAREAH (E.N.S)", "type": "ecole",
      "specializations": ["LANGUE AMAZIGHE(P.E.P)", "LANGUE ANGLAISE(P.E.S)", "HISTOIRE GEOGRAPHIE(P.E.M)", "LANGUE ET LITTERATURE ARABES(P.E.M)", "LANGUE ET LITTERATURE ARABES(P.E.S)"]
    },
    {
      "name": "ECOLE NORMALE SUPERIEURE DE CONSTANTINE (E.N.S)", "type": "ecole",
      "specializations": ["LANGUE ET LITTERATURE ARABES(P.E.M)", "ARABE(P.E.P)", "LANGUE ET LITTERATURE ARABES(P.E.S)"]
    },
    {
      "name": "ECOLE NORMALE SUPERIEURE DE SETIF", "type": "ecole",
      "specializations": ["SCIENCES PHYSIQUE ET TECHNOLOGIE(P.E.M)", "SCIENCES PHYSIQUES(P.E.S.)", "MATHEMATIQUES(P.E.M)", "LANGUE ET LITTERATURE ARABES(P.E.S)"]
    },
    {
      "name": "ECOLE NORMALE SUPERIEURE DE BECHAR", "type": "ecole",
      "specializations": ["PHILOSOPHIE(P.E.S)", "EDUCATION PHYSIQUE ET SPORTIVE(P.E.P)", "LANGUE ET LITTERATURE ARABES(P.E.M)", "SCIENCES PHYSIQUE ET TECHNOLOGIE(P.E.M)", "SCIENCES PHYSIQUES(P.E.S.)", "INFORMATIQUE(P.E.M)", "INFORMATIQUE(P.E.S)", "MATHEMATIQUES(P.E.M)", "MATHEMATIQUES(P.E.S.)", "SCIENCES NATURELLES(P.E.M)", "SCIENCES NATURELLES(P.E.S)", "LANGUE FRANCAISE(P.E.M)", "FRANCAIS(P.E.P)", "LANGUE FRANCAISE(P.E.S)", "LANGUE ANGLAISE(P.E.M)", "LANGUE ANGLAISE(P.E.P)", "LANGUE ANGLAISE(P.E.S)", "ARABE(P.E.P)", "HISTOIRE GEOGRAPHIE(P.E.M)", "HISTOIRE GEOGRAPHIE(P.E.S)"]
    },
    {
      "name": "ECOLE NORMALE SUPERIEURE DE LAGHOUAT", "type": "ecole",
      "specializations": ["LANGUE ET LITTERATURE ARABES(P.E.M)", "ARABE(P.E.P)", "LANGUE ET LITTERATURE ARABES(P.E.S)"]
    },
    {
      "name": "ECOLE NORMALE SUPERIEURE DE SAIDA (E.N.S)", "type": "ecole",
      "specializations": ["SCIENCES PHYSIQUE ET TECHNOLOGIE(P.E.M)"]
    },
    {
      "name": "ECOLE NORMALE SUPERIEURE DE OUARGLA", "type": "ecole",
      "specializations": ["MATHEMATIQUES(P.E.S.)", "SCIENCES NATURELLES(P.E.M)", "SCIENCES NATURELLES(P.E.S)", "LANGUE FRANCAISE(P.E.M)", "LANGUE ET LITTERATURE ARABES(P.E.M)", "ARABE(P.E.P)", "LANGUE ET LITTERATURE ARABES(P.E.S)"]
    },
    {
      "name": "ECOLE NORMALE SUPERIEURE D ORAN", "type": "ecole",
      "specializations": ["SCIENCES PHYSIQUE ET TECHNOLOGIE(P.E.M)"]
    },
    {
      "name": "ECOLE NATIONALE SUPERIEURE D AGRICULTURE SAHARIENNE D ADRAR", "type": "ecole",
      "specializations": ["FB SP ECOLE NATIONALE SUPERIEURE D AGRICULTURE SAHARIENNE D ADRAR"]
    },
    {
      "name": "ECOLE NATIONALE SUPERIEURE D AGRICULTURE SAHARIENNE D EL OUED", "type": "ecole",
      "specializations": ["FB SP ECOLE NATIONALE SUPERIEURE D AGRICULTURE SAHARIENNE D EL OUED"]
    },
    {
      "name": "ECOLE NATIONALE SUPERIEURE DES FORETS KHENCHELA", "type": "ecole",
      "specializations": ["FB SNV ECOLE NATIONALE SUPERIEURE DES FORETS DE KHENCHELA"]
    },
    {
      "name": "ECOLE NATIONALE SUPERIEURE DES ENERGIES RENOUVELABLES DE L ENVIRONNEMENT ET DU DEVELOPPEMENT DURABLE BATNA", "type": "ecole",
      "specializations": ["FB ST ECOLE NAT SUP DES ENERGIES RENOUVELABLES DE ENVIRONNEMENT ET DU DEVELOPPEMENT DURABLE BATNA"]
    },
    {
      "name": "ECOLE SUPERIEURE EN SCIENCES ET TECHNOLOGIES DE L INFORMATIQUE ET DU NUMERIQUE BEJAIA", "type": "ecole",
      "specializations": ["FB INF ECOLE SUPERIEURE EN SCIENCES ET TECHNOLOGIES DE L INFORMATIQUE ET DU NUMERIQUE BEJAIA"]
    },
    {
      "name": "INFSPM ALGER", "type": "ecole",
      "specializations": ["ORTHOPTISTES DE SANTE PUBLIQUE", "ERGOTHERAPEUTES DE SANTE PUBLIQUE", "AUDIOPROTHESISTES DE SANTE PUBLIQUE"]
    },
    {
      "name": "INFSPM JIJEL", "type": "ecole",
      "specializations": ["INFIRMIERS DE SANTE PUBLIQUE", "KINESITHERAPEUTES DE SANTE PUBLIQUE"]
    },
    {
      "name": "RECRUTEMENT NATIONAL", "type": "ecole",
      "specializations": ["MEDECINE", "PHARMACIE", "MEDECINE DENTAIRE"]
    }
  ]
}

    